name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Tarraform
        run: ./bin/install_deb.sh
      - name: Check Formatting
        id: formattingCheck
        run: ./bin/check_formatting.sh
  test:
    name: Test terraform-aws-networking
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Tarraform
        run: ./bin/install_deb.sh
      - name: Run Tests
        run: ./bin/run_tests.sh
